# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d12000665a2a5087ea09269eb8aae94b40155bcf5aee150957672bc5a9178cca6256cc56d91d93d70779ce2c2878f066eccf584e4bd3006adc2a015ed62d36

test:
  secret_key_base: cf88a9b52af60dad6a50416b1a36fd7c49bddd36b7beb50f55ed3beaaeea950edcc244b69b5d521db18df25aad4eee811951b8c8c141f19bc8eb7b40c5171b87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
